# Usar la imagen lastest de mongo
FROM mongo:latest


#  #Variables de entorno para establecer una base de datos y un usuario  de privilegios admin
ENV MONGO_INITDB_ROOT_USERNAME=carlos
ENV MONGO_INITDB_ROOT_PASSWORD=123
ENV MONGO_INITDB_DATABASE=db_Contable

EXPOSE 27017

CMD ["mongod"]